repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      # -------- lint & autofix ------------------------------------
      - id: ruff-check
        args: [--unsafe-fixes, --fix] # auto-fix what can be fixed
        files: ^(amorphouspy/.*\.py|amorphouspy_api/.*\.py|notebooks/.*\.ipynb)$ # staged files in amorphouspy/, amorphouspy_api/, and notebooks/
      # -------- final formatting pass -----------------------------
      - id: ruff-format
        files: ^(amorphouspy/.*\.py|amorphouspy_api/.*\.py|notebooks/.*\.ipynb)$ # staged files in amorphouspy/, amorphouspy_api/, and notebooks/

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
