name: pyiron-glass
channels:
- conda-forge
dependencies:
- python =3.12
- ase >=3.25.0
- hatchling
- jupyter
- lammps =2024.06.27=*_openmpi_*
- networkx ~=3.4
- pandas =2.2.3
- pygraphviz =1.14
- pyiron_atomistics =0.7.7
- pyiron_base =0.12.0
- pyiron-data =0.0.30
- scipy =1.15.2
- structuretoolkit =0.0.32
