name: "amorphouspy: unit tests"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        locked: true
    - name: Run pytest test suite
      run: pixi run test-lib

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: amorphouspy/coverage.xml
        flags: unit
        fail_ci_if_error: false

