name: notebooks for amorphouspy module

on:
  push:
    branches: [ main ]
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  pytest:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.13"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Install dependencies
      working-directory: amorphouspy
      shell: bash -l {0}
      run: |
        pip install hatchling editables
        pip install --no-deps --no-build-isolation -e .
        pip install -r requirements-dev.txt

    - name: Test notebooks
      shell: bash -l {0}
      working-directory: amorphouspy
      run: |
        # absolute path in --cov is necessary here, otherwise it gets confused
        pytest --durations=0 --nbval-lax ../notebooks/*ipynb --cov=$(pwd)/src/amorphouspy --cov-report=term --cov-report=xml --cov-append

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: amorphouspy/coverage.xml


    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: false

