name: jobs for pyrion_glass module

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Run pylint
      shell: bash -l {0}
      run: |
        cd pyiron_glass/
        pip install --no-deps --no-build-isolation -e .
        pip install -r requirements-dev.txt
        python -m pylint src

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Run pytest
      shell: bash -l {0}
      run: |
        cd pyiron_glass/
        pip install --no-deps --no-build-isolation -e .
        pip install -r requirements-dev.txt
        python -m pytest src/tests --cov=src/pyiron_glass --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  melt_quench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Tests
      shell: bash -l {0}
      run: |
        pip install --no-deps --no-build-isolation -e pyiron_glass
        cd notebooks
        papermill Meltquench.ipynb Meltquench_out.ipynb -k "python3"
