name: jobs for pyrion_glass module

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Install dependencies
      working-directory: pyiron_glass
      shell: bash -l {0}
      run: |
        pip install --no-deps --no-build-isolation -e .
        pip install -r requirements-dev.txt
    - name: Run pylint
      shell: bash -l {0}
      working-directory: pyiron_glass
      run: |
        python -m pylint src

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Install dependencies
      working-directory: pyiron_glass
      shell: bash -l {0}
      run: |
        pip install --no-deps --no-build-isolation -e .
        pip install -r requirements-dev.txt
    - name: Run pytest test suite
      shell: bash -l {0}
      working-directory: pyiron_glass
      run: |
        python -m pytest src/tests --cov=src/pyiron_glass --cov-report=xml --cov-report=term

    - name: Test notebooks
      shell: bash -l {0}
      working-directory: pyiron_glass
      run: |
        pytest --nbval-lax ../notebooks/*ipynb --cov=src/pyiron_glass --cov-report=term --cov-report=xml --cov-append

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  # melt_quench:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Conda config
  #     run: echo -e "channels:\n  - conda-forge\n" > .condarc
  #   - uses: conda-incubator/setup-miniconda@v3
  #     with:
  #       python-version: "3.12"
  #       miniforge-version: latest
  #       condarc-file: .condarc
  #       environment-file: environment.yml
  #   - name: Install dependencies
  #     working-directory: pyiron_glass
  #     shell: bash -l {0}
  #     run: |
  #       pip install --no-deps --no-build-isolation -e .
  #       pip install -r requirements-dev.txt
  #   - name: test notebooks
  #     working-directory: pyiron_glass
  #     shell: bash -l {0}
  #     run: |
  #       papermill Meltquench.ipynb Meltquench_out.ipynb -k "python3"
