name: Pipeline for repository-level jobs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.0"
          args: check --output-format=github
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.0"
          args: format --check --diff

  pip_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.13"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Pip check
      shell: bash -l {0}
      run: |
        pip install hatchling editables
        pip install --no-deps --no-build-isolation -e pyiron_glass
        pip install --no-deps --no-build-isolation -e pyiron_glass_api
        pip check
